export const FIND_COURSES_REQUEST = 'FIND_COURSES_BY_CATEGORY_REQUEST';
export const FIND_COURSES_SUCCESS = 'FIND_COURSES_BY_CATEGORY_SUCCESS';
export const FIND_COURSES_FAILURE = 'FIND_COURSES_BY_CATEGORY_FAILURE';

export const FIND_COURSE_BY_ID_REQUEST = 'FIND_COURSES_BY_ID_REQUEST';
export const FIND_COURSE_BY_ID_SUCCESS = 'FIND_COURSES_BY_ID_SUCCESS';
export const FIND_COURSE_BY_ID_FAILURE = 'FIND_COURSES_BY_ID_FAILURE';

export const CREATE_COURSE_REQUEST = 'CREATE_COURSE_REQUEST';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const UPDATE_COURSE_FAILURE = "UPDATE_COURSE_FAILURE";

export const SEARCH_COURSE_REQUEST = "SEARCH_COURSE_REQUEST";
export const SEARCH_COURSE_SUCCESS = "SEARCH_COURSE_SUCCESS";
export const SEARCH_COURSE_FAILURE = "SEARCH_COURSE_FAILURE";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";